name: ZAP Baseline Scan

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

     - name: ZAP Baseline Scan
       uses: zaproxy/action-baseline@v0.11.0
            
        with:
          target: 'https://juice-shop.herokuapp.com/#'
