steps:
  - name: ZAP Scan
    uses: zaproxy/action-baseline@v0.8.0
    with:
      target: 'https://www.zaproxy.org'

name: OWASP ZAP Baseline Scan

on:
  push:
    branches:
      - master

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v0.8.0

        
              - name: ZAP Baseline Scan
                uses: zaproxy/action-baseline@v0.8.0
            
        with:
          target: 'https://juice-shop.herokuapp.com/#'




